import { Character } from './entities/character.entity';

export const major_characters: Character[] = [
  {
    id: 1,
    name: 'Ambrose Jakis',
    age: undefined,
    description:
      "Ambrose's family is currently 12th in the line of succession to the Vintic throne and Kvothe describes him as richer than God. Ambrose has a bad reputation, most specifically for mistreating women. He is depicted as a high ranking gentleman with soft, pale skin and a constant scowl. He writes poetry and is also a Scriv under Master Lorren.",
    hair: undefined,
    eye_color: undefined,
    species: 'Human',
    gender: 'Male',
    ethnicity: 'Vintish',
    occupations: ['University Student', 'Scriv', 'Musician'],
    arcanum_rank: "Re'lar",
  },
  {
    id: 2,
    name: 'Master Arwyl',
    age: undefined,
    description:
      'Master Arwyl is an older man who wears eyeglasses and is described as having a "grandfatherly" appearance, with heavily wrinkled skin and a round face.',
    hair: undefined,
    eye_color: undefined,
    species: 'Human',
    gender: 'Male',
    ethnicity: undefined,
    occupations: ['Physicker', 'Master at the University'],
    arcanum_rank: undefined,
  },
  {
    id: 3,
    name: 'Auri',
    age: undefined,
    description:
      'Auri is a young woman described as appearing a few years older than Kvothe, with blonde hair and a delicate, petite frame. Her hair is long and thin, causing it to float around her head like a halo. She often displays very proper manners and conducts herself with a gentle and careful air. Although she lives in a rather dangerous environment and sometimes displays extremely eccentric behavior, she is very intelligent and quite capable of taking care of herself. She also is shown to be skilled in alchemy and possibly naming. Elodin tells Kvothe that he has known about Auri for years. This along with her young appearance would mean she was inducted in the University at a very young age. This also implies she may be older than she appears. The name Auri is similar to "aureum", which means "gold" or "golden" in Latin. This may be related to her blonde hair. It may also be related to the Quenya Elvish word for "sunlight" which is "árë" as Kvothe bases this name on her "sunny disposition," which in turn is based off the Hebrew word for "light" אוֹר (ohr) or finnish word ,,aurinko" (sun).',
    hair: 'Blond, long',
    eye_color: undefined,
    species: 'Human',
    gender: 'Female',
    ethnicity: undefined,
    occupations: ['University student (former)'],
    arcanum_rank: undefined,
  },
  {
    id: 4,
    name: 'Bast',
    age: '150+',
    description:
      'Bast is first described as dark and charming. He has a quick smile and cunning blue eyes. His features are sharp and delicate, giving him an almost beautiful visage. Bast is later revealed to be a Fae creature under a glamoury. His true appearance is similar except for his eyes become fully blue with no sclera and his boots turn to cloven hooves. He is over 150 years old and a noble of the Faen Courts. His full title is Bastas, Son of Remmen, Prince of Twilight and the Telwyth Mael.',
    hair: 'Dark',
    eye_color: 'Blue',
    species: 'Fae',
    gender: 'Male',
    ethnicity: undefined,
    occupations: [],
    arcanum_rank: undefined,
  },
  {
    id: 5,
    name: 'Bredon',
    age: undefined,
    description:
      "Bredon is a Vintas noble who lives at the Maer's court and befriends Kvothe by teaching him the game of Tak and teaches him the court customs of Vintas. He is described as a gentleman down to his bones, and his hair and beard are pure white, cut to the same length.",
    hair: 'Pure white',
    eye_color: 'Brown',
    species: 'Fae',
    gender: 'Male',
    ethnicity: undefined,
    occupations: [],
    arcanum_rank: undefined,
  },
  {
    id: 6,
    name: 'Denna',
    age: undefined,
    description:
      'Denna is the primary female figure in The Name of the Wind; she is arguably the main romantic interest of Kvothe, who holds an irresistible fascination with her. Due to her chosen lifestyle, she is homeless and prone to wandering but manages to make a decent living using her voice and charm. Men have a fatal attraction to her, an attraction she can never seem to return. When a man gets too familiar with her, she will often leave town quickly and silently. Due to this, she goes by various different names and aliases, including Dianne, Dinnah, Dyanae, Dinael, Dinay, Dianah, Donna, Dyane and Alora.',
    hair: 'Dark, straight',
    eye_color: 'Dark',
    species: 'Human',
    gender: 'Female',
    ethnicity: undefined,
    occupations: ['Courtesan', 'Con Artist', 'Musician'],
    arcanum_rank: undefined,
  },
  {
    id: 7,
    name: 'Dennais Threpe',
    age: undefined,
    description:
      'Count Dennais Threpe is a nobleman who is very fond of art. He acts as a patron, sustaining musicians and other artists as best he is able due to his love of the arts.',
    hair: undefined,
    eye_color: undefined,
    species: 'Human',
    gender: 'Male',
    ethnicity: undefined,
    occupations: ['Nobleman', 'Patron'],
    arcanum_rank: undefined,
  },
  {
    id: 8,
    name: 'Devan Lochees',
    age: undefined,
    description:
      "The Chronicler is an accomplished scrivener, having devised his own shorthand to write as quickly as a man can speak. He travels The Four Corners of Civilization, collecting stories and working as a scribe.  The Chronicler has a fairly scholarly demeanour and is currently the apprentice or colleague of Skarpi.  He is also a member of The Arcanum and one of a handful of people to know the true name of Iron.  Chronicler's real name is Devan Lochees, who is best known in the narrative as the author of The Mating Habits of the Common Draccus.",
    hair: undefined,
    eye_color: undefined,
    species: 'Human',
    gender: 'Male',
    ethnicity: undefined,
    occupations: ['Scribe'],
    arcanum_rank: undefined,
  },
  {
    id: 9,
    name: 'Devi',
    age: undefined,
    description:
      'Devi is described in the books as petite (pixieish) with strawberry-blonde hair. Her face is described as "cute as a button", and she has prominent dimples. She generally portrays a flirtatious demeanor, however is very serious when it comes to business. She is also known by her nickname "demon Devi", which alludes to her amoral, unsympathetic, and business-like approach she takes to her clients. She is quick to anger and slow to forgive. Before being dismissed from The University, Devi had achieved the rank of Re\'lar.',
    hair: 'Red',
    eye_color: 'Blue',
    species: 'Human',
    gender: 'Female',
    ethnicity: undefined,
    occupations: ['Univeristy student (former)', 'Gaelet'],
    arcanum_rank: "Re'lar",
  },
  {
    id: 10,
    name: 'Elodin',
    age: undefined,
    description:
      'Master Elodin was an exceptionally brilliant student and also the youngest to have ever been admitted to the University, at the age of 14. By the time he turned 18, he had become a Full Arcanist and began working as a Giller. He continued on to become Master Namer and then Chancellor of the University, though the latter was short lived. He is at least a dozen years younger than the rest of the Masters in the University and is described as an average looking clean-shaven man. His dark eyes are often depicted as his most striking feature. He is well-known for his eccentric personality and erratic antics, including a habit of going barefoot. This causes some in the University to look down upon him; nevertheless, as befits his position as a Master, he demonstrates an understanding of his respective field of study that few in the modern world can equal. Elodin is best known for his committal and ensuing escape from Haven.',
    hair: 'Dark brown',
    eye_color: 'Dark brown/black',
    species: 'Human',
    gender: 'Male',
    ethnicity: undefined,
    occupations: ['University Master'],
    arcanum_rank: 'Arcanist',
  },
  {
    id: 11,
    name: 'Fela',
    age: undefined,
    description:
      'Fela is described as strikingly beautiful with clear bright eyes and long dark hair. She is very intelligent and works in many different fields of study. Some of these include Artificing, Mathematics, and Naming. She can effectively call the name of stone. She is also a Scriv in the Archives.',
    hair: 'Dark, long',
    eye_color: 'Bright',
    species: 'Human',
    gender: 'Female',
    ethnicity: undefined,
    occupations: ['Univeristy student', 'Scriv'],
    arcanum_rank: "Re'lar",
  },
  {
    id: 12,
    name: 'Felurian',
    age: undefined,
    description:
      'Felurian is a seemingly immortal Fae, known in folktales throughout The Four Corners of Civilization.',
    hair: 'Black, long',
    eye_color: 'Dark',
    species: 'Fae',
    gender: 'Female',
    ethnicity: undefined,
    occupations: [],
    arcanum_rank: undefined,
  },
  {
    id: 13,
    name: 'Kilvin',
    age: undefined,
    description:
      'Kilvin is a Cealdish man with thick shoulders, shaggy hair and a bushy black beard, he is approximately 20 stone in weight (280 lbs). He often surprises Kvothe by displaying a precise memory. He is well versed in artificing and sygaldry. He hopes to one day build an ever-burning lamp, an art he believes has been lost in antiquity.',
    hair: undefined,
    eye_color: undefined,
    species: 'Human',
    gender: 'Male',
    ethnicity: 'Cealdish',
    occupations: ['University master'],
    arcanum_rank: 'Arcanist',
  },
  {
    id: 14,
    name: 'Kvolthe',
    age: "Mid 20's",
    description:
      "Kvothe has pale skin and green eyes, though the intensity of this color is often noted as changing throughout the series. His eyes are similar to the description of his mother's eyes. He has extremely red hair often compared to a flame. He is exceptionally intelligent, quick-witted, sharp-tongued and clever, as well as a talented musician. He is also very curious, a quality that often gets him into trouble. He has a nasty temper, is reckless and often thoughtless.",
    hair: 'Red',
    eye_color: 'Green',
    species: 'Human',
    gender: 'Male',
    ethnicity: 'Edema Ruh',
    occupations: [
      'University student (former)',
      'Musician (former)',
      'Innkeeper',
    ],
    arcanum_rank: "Re'lar",
  },
  {
    id: 15,
    name: 'Lerand Alveron',
    age: '41',
    description:
      'Maer Alveron is described as every bit a king without the crown and title. He has most of the same powers as the King of Vintas, Roderic Calanthis. He is physically described as having a serious and proud face, with a well-trimmed but graying beard. He has thick dark hair with clever and piercing clear grey eyes.',
    hair: 'Dark',
    eye_color: 'Grey',
    species: 'Human',
    gender: 'Male',
    ethnicity: 'Vintish',
    occupations: ['Maershon of Vintas'],
    arcanum_rank: undefined,
  },
  {
    id: 16,
    name: 'Manet',
    age: 'At least 50',
    description:
      'Manet is described as a man of at least 50 years with wild hair and a grizzled beard. He has been at The University for nearly thirty years and consciously avoids moving past the rank of E\'lir. He appears to have no interest in ever being promoted to a full arcanist. Due to this, he is derided by some as "The Eternal E\'lir."',
    hair: 'Grizzled, "Wild"',
    eye_color: undefined,
    species: 'Human',
    gender: 'Male',
    ethnicity: undefined,
    occupations: ['University student'],
    arcanum_rank: "E'lir",
  },
  {
    id: 17,
    name: 'Master Ash',
    age: undefined,
    description:
      'Almost nothing is actually known about Master Ash, which Denna claims is how he prefers to conduct his affairs. However, Denna does reveal he is a dancer in progress and has the appearance of a wealthy gentleman. He is described as being extremely secretive, to the point of outright paranoia and likely carries a cane.',
    hair: 'White',
    eye_color: undefined,
    species: 'Human (likely)',
    gender: 'Male',
    ethnicity: undefined,
    occupations: ['Nobleman (likely)', "Denna's Patron"],
    arcanum_rank: undefined,
  },
  {
    id: 18,
    name: 'Simmon',
    age: undefined,
    description:
      'Simmon is described as an emotional character, with sandy hair and light eyes. He is the fourth son of Duke of Dalonir in the Aturan Empire, and enjoys the gambling game Corners and hates to lose bets. He is 3 years older than Kvothe.',
    hair: 'Sandy',
    eye_color: 'Light',
    species: 'Human',
    gender: 'Male',
    ethnicity: 'Aturan',
    occupations: ['University student'],
    arcanum_rank: "Re'lar",
  },
  {
    id: 19,
    name: 'Tempi',
    age: undefined,
    description:
      'Tempi is a quiet man, who rarely makes eye contact. He is very fair complected, lean, and sleek. He has pale grey eyes and sandy hair. Though his Aturan is poor it slowly improves as he travels with Kvothe. Tempi is a relatively young and inexperienced mercenary by the standards of the Adem, but he easily defeats three "barbarian" mercenaries when challenged in unarmed combat.',
    hair: 'Light',
    eye_color: 'Grey',
    species: 'Human',
    gender: 'Male',
    ethnicity: 'Adem',
    occupations: ['Adem Mercenary'],
    arcanum_rank: undefined,
  },
  {
    id: 20,
    name: 'Wilem',
    age: undefined,
    description:
      "Wilem is a young Cealdish man with the typical dark complexion that befits his ancestry. He is the son of wool merchants from Ralien and has a very strong accent, naturally speaking Siaru, the first language in The Ceald. Wilem is a generally stoic character, though does enjoy the company of Simmon, Kvothe, and Manet very much; often delighting in drinks with them at different taverns near the University. Specifically, Wilem enjoys drinking scutten, also called Cut-Tail and playing the betting game corners. At the University, Wilem works as one of Master Lorren's Scrivs as well as attending classes.",
    hair: 'Dark',
    eye_color: 'Dark',
    species: 'Human',
    gender: 'Male',
    ethnicity: 'Cealdish',
    occupations: ['University student', 'Scriv'],
    arcanum_rank: undefined,
  },
  {
    id: 21,
    name: 'The Cthaeh',
    age: undefined,
    description:
      'The Cthaeh is generally regarded by the Fae as the most terrible and malicious being in existence. The Cthaeh is a creature who dwells within the branches of a great tree, located in the middle of a clearing in the Fae Realm. It is either trapped or forced to stay there by the guardians of the tree, The Sithe. It is known to converse with those who approach it, often displaying a sort of omniscience about the world and the life of the visitor. According to Bast, the Cthaeh is poisonous, hateful and contagious. It can see all possible futures with perfect accuracy and clarity, branching out from a single moment. It uses this knowledge to cause the worst possible outcomes for as many people as possible. In doing so it often reveals information that will hurt and traumatize those who speak to it. It does so on purpose, since it is regarded as very cruel and malevolent.',
    hair: undefined,
    eye_color: undefined,
    species: 'Unknown',
    gender: undefined,
    ethnicity: 'Fae',
    occupations: [
      'Seeing *all* of the future',
      'Causing tragedy',
      'Leaving men broken',
    ],
    arcanum_rank: undefined,
  },
  {
    id: 22,
    name: 'Haliax',
    age: 'Five thousand',
    description:
      "Haliax is the leader of The Chandrian, and one of the major antagonists of Kvothe's storyline. Haliax's most distinguishing feature is that he is completely obscured by shadow even in broad daylight. He wears a discernible cowl, but the rest of him is like looking down a well at midnight. He is described by the Adem as the Shadow-Hamed and it is believed he does not sleep or forget. It is suggested throughout the Chronicle that Haliax cannot be permanently killed by any known means. He displays great power at naming and is also able to become a black shadow the other members of the Chandrian appear to use as a method of transportation.",
    hair: undefined,
    eye_color: undefined,
    species: 'Humanoid',
    gender: 'Male',
    ethnicity: undefined,
    occupations: ['Leader of The Chandrian'],
    arcanum_rank: undefined,
  },
  {
    id: 23,
    name: 'Abenthy',
    age: undefined,
    description:
      'Abenthy is described as an older, portly gentlemen with twinkling eyes. He has greying hair, and most prominently, eyebrows that are in a perpetual state of regrowth. He drives a wagon pulled by two donkeys, Alpha and Beta. He is a full arcanist from The University. He sings in a tenor voice that tends to go wandering off looking for notes.',
    hair: 'Grey',
    eye_color: undefined,
    species: 'Human',
    gender: 'Male',
    ethnicity: undefined,
    occupations: ["Kvothe's teacher (formerly)"],
    arcanum_rank: 'Arcanist',
  },
];
